# Generated by Django 5.1.15 on 2026-05-29 07:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("channels_app", "0007_channel_collaborations_open"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ContentFlag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("avatar", "Avatar"),
                            ("banner", "Bannière"),
                            ("thumbnail", "Vignette"),
                            ("title", "Titre de stream"),
                            ("bio", "Bio"),
                            ("tag", "Tag"),
                            ("game_art", "Box art jeu"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("safe", "Sain"),
                            ("sexual", "Sexuel / pornographie"),
                            ("gore", "Gore / violence"),
                            ("other", "Autre"),
                        ],
                        db_index=True,
                        max_length=12,
                    ),
                ),
                ("confidence", models.FloatField(default=0.0)),
                ("text", models.CharField(blank=True, max_length=500)),
                ("url", models.URLField(blank=True, max_length=500)),
                ("scores", models.JSONField(blank=True, default=dict)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "À examiner"),
                            ("auto_blocked", "Bloqué auto."),
                            ("approved", "Approuvé"),
                            ("rejected", "Rejeté"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=14,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                (
                    "channel",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="content_flags",
                        to="channels_app.channel",
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="content_flags",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["status", "category"], name="safety_cont_status_74f9bb_idx"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="RiskEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("tip_velocity", "Tips trop rapides"),
                            ("self_deal", "Auto-transaction"),
                            ("follow_velocity", "Follows trop rapides"),
                            ("multi_account", "Multi-comptes (IP partagée)"),
                            ("view_inflation", "Gonflage de vues"),
                            ("sub_abuse", "Abus d'abonnement"),
                        ],
                        db_index=True,
                        max_length=24,
                    ),
                ),
                (
                    "severity",
                    models.PositiveSmallIntegerField(
                        choices=[(1, "Faible"), (2, "Moyen"), (3, "Élevé")],
                        db_index=True,
                        default=1,
                    ),
                ),
                ("detail", models.JSONField(blank=True, default=dict)),
                ("resolved", models.BooleanField(db_index=True, default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="risk_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["user", "kind"], name="safety_risk_user_id_557089_idx")
                ],
            },
        ),
    ]
